/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GradientsRouteImport } from './routes/gradients'
import { Route as PalettesRouteImport } from './routes/palettes'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GradientsRoute = GradientsRouteImport.update({
  id: '/gradients',
  path: '/gradients',
  getParentRoute: () => rootRouteImport,
} as any)
const PalettesRoute = PalettesRouteImport.update({
  id: '/palettes',
  path: '/palettes',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/gradients': typeof GradientsRoute
  '/palettes': typeof PalettesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/gradients': typeof GradientsRoute
  '/palettes': typeof PalettesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/gradients': typeof GradientsRoute
  '/palettes': typeof PalettesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/gradients' | '/palettes'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/gradients' | '/palettes'
  id: '__root__' | '/' | '/gradients' | '/palettes'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GradientsRoute: typeof GradientsRoute
  PalettesRoute: typeof PalettesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gradients': {
      id: '/gradients'
      path: '/gradients'
      fullPath: '/gradients'
      preLoaderRoute: typeof GradientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/palettes': {
      id: '/palettes'
      path: '/palettes'
      fullPath: '/palettes'
      preLoaderRoute: typeof PalettesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GradientsRoute: GradientsRoute,
  PalettesRoute: PalettesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
